### ISSUE TITLE
Won't install using npm on win10

### ISSUE THREAD

**Issue by garymazz** [googlemaps/v3-utility-library#675]
I need help getting this to work... 

I just tried installing using command line:

`npm i @google/markerclustererplus `

I get an error:
```
npm WARN deprecated @google/markerclustererplus@5.1.3: This package has moved to @googlemaps/markerclustererplus and the source is now at https://github.com/googlemaps/js-markerclustererplus.
npm WARN deprecated eslint-loader@3.0.4: This loader has been deprecated. Please use eslint-webpack-plugin
npm ERR! Cannot read property 'match' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aa\AppData\Roaming\npm-cache\_logs\2020-11-19T21_46_50_080Z-debug.log
```
The detailed log:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'M:\\nodejs\\node.exe',
1 verbose cli   'M:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '@google/markerclustererplus'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose npm-session 0b0ac17108653069
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/@google%2fmarkerclustererplus 880ms (from cache)
8 silly pacote tag manifest for @google/markerclustererplus@latest fetched in 894ms
9 warn deprecated @google/markerclustererplus@5.1.3: This package has moved to @googlemaps/markerclustererplus and the source is now at https://github.com/googlemaps/js-markerclustererplus.
10 timing stage:loadCurrentTree Completed in 2675ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 14ms
14 silly install loadShrinkwrap
15 http fetch GET 304 https://registry.npmjs.org/@quasar%2fapp 141ms (from cache)
16 silly pacote version manifest for @quasar/app@2.0.8 fetched in 147ms
17 http fetch GET 304 https://registry.npmjs.org/@quasar%2fextras 125ms (from cache)
18 silly pacote version manifest for @quasar/extras@1.9.5 fetched in 127ms
19 http fetch GET 304 https://registry.npmjs.org/@quasar%2fquasar-app-extension-qpdfviewer 147ms (from cache)
20 silly pacote version manifest for @quasar/quasar-app-extension-qpdfviewer@1.0.0-beta.8 fetched in 149ms
21 http fetch GET 304 https://registry.npmjs.org/babel-eslint 31ms (from cache)
22 silly pacote version manifest for babel-eslint@10.1.0 fetched in 33ms
23 http fetch GET 304 https://registry.npmjs.org/eslint 39ms (from cache)
24 silly pacote version manifest for eslint@6.8.0 fetched in 45ms
25 http fetch GET 304 https://registry.npmjs.org/eslint-config-standard 43ms (from cache)
26 silly pacote version manifest for eslint-config-standard@14.1.1 fetched in 45ms
27 http fetch GET 304 https://registry.npmjs.org/eslint-loader 48ms (from cache)
28 silly pacote version manifest for eslint-loader@3.0.4 fetched in 49ms
29 warn deprecated eslint-loader@3.0.4: This loader has been deprecated. Please use eslint-webpack-plugin
30 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-import 29ms (from cache)
31 silly pacote version manifest for eslint-plugin-import@2.22.0 fetched in 32ms
32 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-node 32ms (from cache)
33 silly pacote version manifest for eslint-plugin-node@11.1.0 fetched in 34ms
34 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-promise 27ms (from cache)
35 silly pacote version manifest for eslint-plugin-promise@4.2.1 fetched in 28ms
36 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-standard 34ms (from cache)
37 silly pacote version manifest for eslint-plugin-standard@4.0.1 fetched in 36ms
38 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-vue 40ms (from cache)
39 silly pacote version manifest for eslint-plugin-vue@6.2.2 fetched in 42ms
40 http fetch GET 304 https://registry.npmjs.org/quasar 31ms (from cache)
41 silly pacote version manifest for quasar@1.13.1 fetched in 36ms
42 http fetch GET 304 https://registry.npmjs.org/quasar-app-extension-vuelidate-rules 27ms (from cache)
43 silly pacote version manifest for quasar-app-extension-vuelidate-rules@0.3.1 fetched in 28ms
44 timing stage:rollbackFailedOptional Completed in 0ms
45 timing stage:runTopLevelLifecycles Completed in 4071ms
46 silly saveTree OEData-Workbench-Manager@0.0.1
46 silly saveTree +-- @quasar/quasar-app-extension-qpdfviewer@1.0.0-beta.8
46 silly saveTree +-- babel-eslint@10.1.0
46 silly saveTree | +-- @babel/code-frame@7.10.4
46 silly saveTree | | `-- @babel/highlight@7.10.4
46 silly saveTree | |   +-- @babel/helper-validator-identifier@7.10.4
46 silly saveTree | |   +-- chalk@2.4.2
46 silly saveTree | |   | +-- ansi-styles@3.2.1
46 silly saveTree | |   | | `-- color-convert@1.9.3
46 silly saveTree | |   | |   `-- color-name@1.1.3
46 silly saveTree | |   | +-- escape-string-regexp@1.0.5
46 silly saveTree | |   | `-- supports-color@5.5.0
46 silly saveTree | |   |   `-- has-flag@3.0.0
46 silly saveTree | |   `-- js-tokens@4.0.0
46 silly saveTree | +-- @babel/parser@7.12.5
46 silly saveTree | +-- @babel/traverse@7.12.5
46 silly saveTree | | +-- @babel/generator@7.12.5
46 silly saveTree | | | +-- @babel/types@7.12.6
46 silly saveTree | | | | +-- lodash@4.17.20
46 silly saveTree | | | | `-- to-fast-properties@2.0.0
46 silly saveTree | | | +-- jsesc@2.5.2
46 silly saveTree | | | `-- source-map@0.5.7
46 silly saveTree | | +-- @babel/helper-function-name@7.10.4
46 silly saveTree | | | +-- @babel/helper-get-function-arity@7.10.4
46 silly saveTree | | | `-- @babel/template@7.10.4
46 silly saveTree | | +-- @babel/helper-split-export-declaration@7.11.0
46 silly saveTree | | +-- @babel/types@7.12.6
46 silly saveTree | | +-- debug@4.3.1
46 silly saveTree | | | `-- ms@2.1.2
46 silly saveTree | | +-- globals@11.12.0
46 silly saveTree | | `-- lodash@4.17.20
46 silly saveTree | +-- @babel/types@7.12.6
46 silly saveTree | +-- eslint-visitor-keys@1.3.0
46 silly saveTree | `-- resolve@1.19.0
46 silly saveTree |   +-- is-core-module@2.1.0
46 silly saveTree |   | `-- has@1.0.3
46 silly saveTree |   |   `-- function-bind@1.1.1
46 silly saveTree |   `-- path-parse@1.0.6
46 silly saveTree +-- core-js@3.7.0
46 silly saveTree +-- eslint-plugin-node@11.1.0
46 silly saveTree | +-- eslint-plugin-es@3.0.1
46 silly saveTree | | +-- eslint-utils@2.1.0
46 silly saveTree | | `-- regexpp@3.1.0
46 silly saveTree | +-- eslint-utils@2.1.0
46 silly saveTree | +-- ignore@5.1.8
46 silly saveTree | +-- minimatch@3.0.4
46 silly saveTree | | `-- brace-expansion@1.1.11
46 silly saveTree | |   +-- balanced-match@1.0.0
46 silly saveTree | |   `-- concat-map@0.0.1
46 silly saveTree | `-- semver@6.3.0
46 silly saveTree +-- eslint-plugin-promise@4.2.1
46 silly saveTree `-- quasar-app-extension-vuelidate-rules@0.3.1
46 silly saveTree   `-- vuelidate@0.7.6
47 verbose stack TypeError: Cannot read property 'match' of undefined
47 verbose stack     at tarballToVersion (M:\nodejs\node_modules\npm\lib\install\inflate-shrinkwrap.js:87:20)
47 verbose stack     at inflatableChild (M:\nodejs\node_modules\npm\lib\install\inflate-shrinkwrap.js:113:22)
47 verbose stack     at M:\nodejs\node_modules\npm\lib\install\inflate-shrinkwrap.js:55:12
47 verbose stack     at tryCatcher (M:\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
47 verbose stack     at Object.gotValue (M:\nodejs\node_modules\npm\node_modules\bluebird\js\release\reduce.js:155:18)
47 verbose stack     at Object.gotAccum (M:\nodejs\node_modules\npm\node_modules\bluebird\js\release\reduce.js:144:25)
47 verbose stack     at Object.tryCatcher (M:\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
47 verbose stack     at Promise._settlePromiseFromHandler (M:\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:517:31)
47 verbose stack     at Promise._settlePromise (M:\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:574:18)
47 verbose stack     at Promise._settlePromise0 (M:\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:619:10)
47 verbose stack     at Promise._settlePromises (M:\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:699:18)
47 verbose stack     at _drainQueueStep (M:\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
47 verbose stack     at _drainQueue (M:\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
47 verbose stack     at Async._drainQueues (M:\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
47 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (M:\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
47 verbose stack     at processImmediate (internal/timers.js:456:21)
48 verbose cwd C:\Users\aa\workbench
49 verbose Windows_NT 10.0.18363
50 verbose argv "M:\\nodejs\\node.exe" "M:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "@google/markerclustererplus"
51 verbose node v12.18.3
52 verbose npm  v6.14.6
53 error Cannot read property 'match' of undefined
54 verbose exit [ 1, true ]

```

**Comment by jpoehnelt** [comment]
What happens if you install `@googlemaps/markerclustererplus`?

**Comment by garymazz** [comment]
@jpoehnelt  The same...

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'M:\\nodejs\\node.exe',
1 verbose cli   'M:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '@googlemaps/markerclustererplus'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose npm-session 1e218b92a7441b98
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/@googlemaps%2fmarkerclustererplus 300ms (from cache)
8 silly pacote tag manifest for @googlemaps/markerclustererplus@latest fetched in 313ms
9 timing stage:loadCurrentTree Completed in 2254ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 15ms
13 silly install loadShrinkwrap
14 http fetch GET 304 https://registry.npmjs.org/@quasar%2fapp 159ms (from cache)
15 silly pacote version manifest for @quasar/app@2.0.8 fetched in 170ms
16 http fetch GET 304 https://registry.npmjs.org/@quasar%2fextras 159ms (from cache)
17 silly pacote version manifest for @quasar/extras@1.9.5 fetched in 163ms
18 http fetch GET 304 https://registry.npmjs.org/@quasar%2fquasar-app-extension-qpdfviewer 180ms (from cache)
19 silly pacote version manifest for @quasar/quasar-app-extension-qpdfviewer@1.0.0-beta.8 fetched in 184ms
20 http fetch GET 304 https://registry.npmjs.org/babel-eslint 30ms (from cache)
21 silly pacote version manifest for babel-eslint@10.1.0 fetched in 32ms
22 http fetch GET 304 https://registry.npmjs.org/eslint 30ms (from cache)
23 silly pacote version manifest for eslint@6.8.0 fetched in 37ms
24 http fetch GET 304 https://registry.npmjs.org/eslint-config-standard 57ms (from cache)
25 silly pacote version manifest for eslint-config-standard@14.1.1 fetched in 60ms
26 http fetch GET 304 https://registry.npmjs.org/eslint-loader 27ms (from cache)
27 silly pacote version manifest for eslint-loader@3.0.4 fetched in 29ms
28 warn deprecated eslint-loader@3.0.4: This loader has been deprecated. Please use eslint-webpack-plugin
29 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-import 38ms (from cache)
30 silly pacote version manifest for eslint-plugin-import@2.22.0 fetched in 40ms
31 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-node 28ms (from cache)
32 silly pacote version manifest for eslint-plugin-node@11.1.0 fetched in 30ms
33 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-promise 26ms (from cache)
34 silly pacote version manifest for eslint-plugin-promise@4.2.1 fetched in 28ms
35 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-standard 38ms (from cache)
36 silly pacote version manifest for eslint-plugin-standard@4.0.1 fetched in 39ms
37 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-vue 129ms (from cache)
38 silly pacote version manifest for eslint-plugin-vue@6.2.2 fetched in 136ms
39 http fetch GET 304 https://registry.npmjs.org/quasar 30ms (from cache)
40 silly pacote version manifest for quasar@1.13.1 fetched in 35ms
41 http fetch GET 304 https://registry.npmjs.org/quasar-app-extension-vuelidate-rules 31ms (from cache)
42 silly pacote version manifest for quasar-app-extension-vuelidate-rules@0.3.1 fetched in 32ms
43 timing stage:rollbackFailedOptional Completed in 0ms
44 timing stage:runTopLevelLifecycles Completed in 3888ms
45 silly saveTree OEData-Workbench-Manager@0.0.1
45 silly saveTree +-- @quasar/quasar-app-extension-qpdfviewer@1.0.0-beta.8
45 silly saveTree +-- babel-eslint@10.1.0
45 silly saveTree | +-- @babel/code-frame@7.10.4
45 silly saveTree | | `-- @babel/highlight@7.10.4
45 silly saveTree | |   +-- @babel/helper-validator-identifier@7.10.4
45 silly saveTree | |   +-- chalk@2.4.2
45 silly saveTree | |   | +-- ansi-styles@3.2.1
45 silly saveTree | |   | | `-- color-convert@1.9.3
45 silly saveTree | |   | |   `-- color-name@1.1.3
45 silly saveTree | |   | +-- escape-string-regexp@1.0.5
45 silly saveTree | |   | `-- supports-color@5.5.0
45 silly saveTree | |   |   `-- has-flag@3.0.0
45 silly saveTree | |   `-- js-tokens@4.0.0
45 silly saveTree | +-- @babel/parser@7.12.5
45 silly saveTree | +-- @babel/traverse@7.12.5
45 silly saveTree | | +-- @babel/generator@7.12.5
45 silly saveTree | | | +-- @babel/types@7.12.6
45 silly saveTree | | | | +-- lodash@4.17.20
45 silly saveTree | | | | `-- to-fast-properties@2.0.0
45 silly saveTree | | | +-- jsesc@2.5.2
45 silly saveTree | | | `-- source-map@0.5.7
45 silly saveTree | | +-- @babel/helper-function-name@7.10.4
45 silly saveTree | | | +-- @babel/helper-get-function-arity@7.10.4
45 silly saveTree | | | `-- @babel/template@7.10.4
45 silly saveTree | | +-- @babel/helper-split-export-declaration@7.11.0
45 silly saveTree | | +-- @babel/types@7.12.6
45 silly saveTree | | +-- debug@4.3.1
45 silly saveTree | | | `-- ms@2.1.2
45 silly saveTree | | +-- globals@11.12.0
45 silly saveTree | | `-- lodash@4.17.20
45 silly saveTree | +-- @babel/types@7.12.6
45 silly saveTree | +-- eslint-visitor-keys@1.3.0
45 silly saveTree | `-- resolve@1.19.0
45 silly saveTree |   +-- is-core-module@2.1.0
45 silly saveTree |   | `-- has@1.0.3
45 silly saveTree |   |   `-- function-bind@1.1.1
45 silly saveTree |   `-- path-parse@1.0.6
45 silly saveTree +-- core-js@3.7.0
45 silly saveTree +-- eslint-plugin-node@11.1.0
45 silly saveTree | +-- eslint-plugin-es@3.0.1
45 silly saveTree | | +-- eslint-utils@2.1.0
45 silly saveTree | | `-- regexpp@3.1.0
45 silly saveTree | +-- eslint-utils@2.1.0
45 silly saveTree | +-- ignore@5.1.8
45 silly saveTree | +-- minimatch@3.0.4
45 silly saveTree | | `-- brace-expansion@1.1.11
45 silly saveTree | |   +-- balanced-match@1.0.0
45 silly saveTree | |   `-- concat-map@0.0.1
45 silly saveTree | `-- semver@6.3.0
45 silly saveTree +-- eslint-plugin-promise@4.2.1
45 silly saveTree `-- quasar-app-extension-vuelidate-rules@0.3.1
45 silly saveTree   `-- vuelidate@0.7.6
46 verbose stack TypeError: Cannot read property 'match' of undefined
46 verbose stack     at tarballToVersion (M:\nodejs\node_modules\npm\lib\install\inflate-shrinkwrap.js:87:20)
46 verbose stack     at inflatableChild (M:\nodejs\node_modules\npm\lib\install\inflate-shrinkwrap.js:113:22)
46 verbose stack     at M:\nodejs\node_modules\npm\lib\install\inflate-shrinkwrap.js:55:12
46 verbose stack     at tryCatcher (M:\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
46 verbose stack     at Object.gotValue (M:\nodejs\node_modules\npm\node_modules\bluebird\js\release\reduce.js:155:18)
46 verbose stack     at Object.gotAccum (M:\nodejs\node_modules\npm\node_modules\bluebird\js\release\reduce.js:144:25)
46 verbose stack     at Object.tryCatcher (M:\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
46 verbose stack     at Promise._settlePromiseFromHandler (M:\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:517:31)
46 verbose stack     at Promise._settlePromise (M:\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:574:18)
46 verbose stack     at Promise._settlePromise0 (M:\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:619:10)
46 verbose stack     at Promise._settlePromises (M:\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:699:18)
46 verbose stack     at _drainQueueStep (M:\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
46 verbose stack     at _drainQueue (M:\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
46 verbose stack     at Async._drainQueues (M:\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
46 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (M:\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
46 verbose stack     at processImmediate (internal/timers.js:456:21)
47 verbose cwd C:\Users\aa\workbench
48 verbose Windows_NT 10.0.18363
49 verbose argv "M:\\nodejs\\node.exe" "M:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "@googlemaps/markerclustererplus"
50 verbose node v12.18.3
51 verbose npm  v6.14.6
5
2 error Cannot read property 'match' of undefined
53 verbose exit [ 1, true ]
```

**Comment by jpoehnelt** [comment]
I would suggest starting with a clean environment and adding other dependencies. I think you might have something else causing the issue.

**Comment by garymazz** [comment]
Yeah,  I'm using quasar framework due to project requirement. I just recreated using clean projects. Both yarn and npm install worked.  As apps become increasingly complex, you may want to consider some pre-installation utility validation like we did in the "olden days" with 'make'.  :)
